src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 * @UniqueEntity("title")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=5)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\Length(min=5)
     */
    private $short_description;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20)
     */
    private $long_description;

    /**
     * @ORM\Column(type="decimal", scale=2 )
     * @Assert\Positive
     */
    private $price;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $soldout = false;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $promo = false;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getLongDescription(): ?string
    {
        return $this->long_description;
    }

    public function setLongDescription(string $long_description): self
    {
        $this->long_description = $long_description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getFormattedPrice(): string
    {
        return number_format($this->price, 2, ',', ' ');
    }

    public function getSoldout(): ?bool
    {
        return $this->soldout;
    }

    public function setSoldout(bool $soldout): self
    {
        $this->soldout = $soldout;

        return $this;
    }

    public function getPromo(): ?bool
    {
        return $this->promo;
    }

    public function setPromo(bool $promo): self
    {
        $this->promo = $promo;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('short_description')
            ->add('long_description')
            ->add('price', MoneyType::class, [
                'currency' => 'EUR'
            ])
            ->add('soldout')
            ->add('promo')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
            'translation_domain' => 'forms'
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints as Assert;

class ProductController extends AbstractController
{
    /**
     * @var ProductRepository
     */
    private $repository;

    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(ProductRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/nos-produits/accueil", name="product.index")
     * @return Response
     */
    public function index(): Response
    {
        return $this->render('product/index.html.twig', [
            'current_menu' => 'products'
        ]);
    }

    /**
     * @Route("/nos-produits/{slug}-{id}", name="product.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Product $product
     * @return Response
     */
    public function show(Product $product, string $slug): Response
    {
        if($product->getSlug() !== $slug) {
            $this->redirectToRoute('product.show', [
                'id' => $product->getId(),
                'slug' => $product->getSlug()
            ], 301);
        }
        return $this->render('product/show.html.twig', [
            'product' => $product,
            'current_menu' => 'products'
        ]);
    }

}

templates/product/index.html.twig
{% extends 'base.html.twig' %}
{% block title 'Boutique en ligne - Produits entretien, cosmétiques, bien-être écologique | Green And Care' %}
{% block body %}
    <div class="container mt-4">
<h1>LA BOUTIQUE GREEN AND CARE</h1>
    </div>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title product.title %}

{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h1>{{ product.title }}</h1>
                    <img src="#" alt="">
                </div>
                <div class="col-md-6">
                    <h2>{{ product.shortDescription }}</h2>
                    <p>{{ product.longDescription | nl2br }}</p>
                    <p class="text-primary">{{ product.formattedPrice }} €</p>
                    <select class="custom-select col-md-2">
                        <option selected value="1">1</option>
                        <option selected value="2">2</option>
                        <option selected value="3">3</option>
                        <option selected value="4">4</option>
                        <option selected value="5">5</option>
                    </select>
                    <a href="" class="btn btn-primary">Ajouter au panier</a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">

    </div>

{% endblock %}